### ISSUE TITLE
JSONDecodeError in parsing solution (or-tools)

### ISSUE THREAD

**Issue by alexeytref** [MiniZinc/minizinc-python#51]
I have an error like this:
```
  File "C:\AlexeyFolder\ProductOptimization\base_solver.py", line 360, in solve
    async for res in self.instance.solutions(**self.run_parameters):
  File "C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\CLI\instance.py", line 382, in solutions
    solution, statistics = parse_solution(
  File "C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\result.py", line 335, in parse_solution
    tmp = json.loads(raw, enum_map=enum_map, cls=MZNJSONDecoder)
  File "C:\Users\Администратор.WIN-GHJQMNTKAB5\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "C:\Users\Администратор.WIN-GHJQMNTKAB5\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Администратор.WIN-GHJQMNTKAB5\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 234 (char 49151)
```
To understand it, I tried to export raw from result.py:
[raw_fail.zip](https://github.com/MiniZinc/minizinc-python/files/8252072/raw_fail.zip)
It seems that because of the time limit, the output of the solution by or-tools was interrupted in the middle.
Am I right? Is there anything you can do about it on your side?
Minizinc 2.6.0
minizinc package 0.4.2
or-tools 9.0.9048

**Comment by Dekker1** [comment]
Could you try updating MiniZinc Python to the newest version (0.6.0)? Likely this is an issue where or tools has unexpected output, but maybe leveraging the MiniZinc json streams that that recently been introduced might avoid the problem

**Comment by alexeytref** [comment]
After the update, I got another error. Is it the same nature?
```
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\json.py:91: MiniZincWarning: model inconsistency detected: domain is empty
  warnings.warn(obj["message"], MiniZincWarning)
Traceback (most recent call last):
  File "C:\AlexeyFolder\ProductOptimization\product_optimization_solver\brick_solver.py", line 253, in solve
    await super().solve()
  File "C:\AlexeyFolder\ProductOptimization\base_solver.py", line 360, in solve
    async for res in self.instance.solutions(**self.run_parameters):
  File "C:\Users\0F15~1.WIN\AppData\Local\pypoetry\Cache\virtualenvs\opti-bed-solvers-8romFmtb-py3.9\lib\site-packages\minizinc\CLI\instance.py", line 441, in solutions
    raise parse_error(stderr)
minizinc.error.MiniZincError: MiniZinc error: Memory violation detected (segmentation fault).
This is a bug. Please file a bug report using the MiniZinc bug tracker.
```

**Comment by Dekker1** [comment]
No, this error appears to be a bug in the MiniZinc compiler. If you can minimise the model, then this issue would be a perfect fit for the https://github.com/MiniZinc/libminizinc repository
