### ISSUE TITLE
Example not working (AttributeError: partially initialized module 'minizinc' has no attribute 'Model')

### ISSUE THREAD

**Issue by m-ober** [MiniZinc/minizinc-python#52]
Running the example from the README does not work for me.

Ubuntu 20.04.3 LTS
Python 3.8.10
MiniZinc 2.6.2

The error is:

```
/bin/python3 /home/ubuntu/workspace/minizinc.py
Traceback (most recent call last):
  File "/home/ubuntu/workspace/minizinc.py", line 1, in <module>
    import minizinc
  File "/home/ubuntu/workspace/minizinc.py", line 4, in <module>
    model = minizinc.Model()
AttributeError: partially initialized module 'minizinc' has no attribute 'Model' (most likely due to a circular import)
```

**Comment by Dekker1** [comment]
The problem is that you named your own file “minizinc.py” so as the error message suggests, it is incorrectly importing itself. Renaming the file should resolve the issue.
