### ISSUE TITLE
test_checker/test_no_output_checker fail on aarch64 and ppc64le

### ISSUE THREAD

**Issue by StefanBruens** [MiniZinc/minizinc-python#64]
```
[   27s] =========================== short test summary info ============================
[   27s] FAILED tests/test_solving.py::TestChecker::test_checker - minizinc.error.Mini...
[   27s] FAILED tests/test_solving.py::TestChecker::test_no_output_checker - minizinc....
[   27s] ======= 2 failed, 48 passed, 1 skipped, 8 deselected, 1 warning in 8.02s =======
```

```
[   27s] ___________________________ TestChecker.test_checker ___________________________
[   27s] 
[   27s] self = <test_solving.TestChecker testMethod=test_checker>
[   27s] 
[   27s]     def test_checker(self):
[   27s]         try:
[   27s]             checker = tempfile.NamedTemporaryFile(
[   27s]                 prefix="checker_test_", suffix=".mzc.mzn", delete=False
[   27s]             )
[   27s]             checker.write(b'output["SIMPLE CHECK"];\n')
[   27s]             checker.close()
[   27s]             self.instance.add_file(checker.name)
[   27s]             assert self.instance.method == Method.SATISFY
[   27s] >           result = self.instance.solve()
[   27s] 
[   27s] tests/test_solving.py:55: 
[   27s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   27s] ../../BUILDROOT/python-minizinc-0.7.0-4.1.aarch64/usr/lib/python3.8/site-packages/minizinc/instance.py:186: in solve
[   27s]     return asyncio.run(coroutine)
[   27s] /usr/lib64/python3.8/asyncio/runners.py:44: in run
[   27s]     return loop.run_until_complete(main)
[   27s] /usr/lib64/python3.8/asyncio/base_events.py:616: in run_until_complete
[   27s]     return future.result()
[   27s] ../../BUILDROOT/python-minizinc-0.7.0-4.1.aarch64/usr/lib/python3.8/site-packages/minizinc/instance.py:250: in solve_async
[   27s]     async for result in self.solutions(
[   27s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   27s] 
[   27s] self = <minizinc.instance.Instance object at 0xffff918e70a0>, timeout = None
[   27s] nr_solutions = None, processes = None, random_seed = None, all_solutions = False
[   27s] intermediate_solutions = False, free_search = False, optimisation_level = None
[   27s] verbose = False, debug_output = None, kwargs = {}, method = <Method.SATISFY: 1>
[   27s] cmd = ['--output-mode', 'json', '--output-time', '--output-objective', '--output-output-item', '--statistics', ...]
[   27s] files = [PosixPath('/tmp/checker_test_3iyhihiu.mzc.mzn'), PosixPath('/tmp/mzn_fragment3q5stucn.mzn')]
[   27s] solver = 'org.gecode.gecode@6.3.0', status = <Status.UNKNOWN: 2>
...
[   27s]             # Raise error if required
[   27s]             stderr = await read_stderr
[   27s]             if code != 0 or status == Status.ERROR:
[   27s] >               raise parse_error(stderr)
[   27s] E               minizinc.error.MiniZincError: UNKNOWN EXCEPTION.
[   27s] 
[   27s] ../../BUILDROOT/python-minizinc-0.7.0-4.1.aarch64/usr/lib/python3.8/site-packages/minizinc/instance.py:465: MiniZincError
```

This is apparently an unhandled error/exception in minizinc itself:
https://github.com/MiniZinc/libminizinc/blob/0b19fb039afff495832ae48f4c206f2653862bb4/minizinc.cpp#L71
```
    } catch (...) {
      if (slv.getFlagVerbose()) {
        std::cerr << std::endl;
      }
      std::cerr << "  UNKNOWN EXCEPTION." << std::endl;
    }
```

Trying to reproduce this with minizinc directly has not provided any insight, the following two calls (which should be equivalent to the wrapped calls from python) succeed:
```
cat > t1.mzn <<EOF
var 1..5: x;
output["SIMPLE CHECK"];
EOF
cat > t2.mzn <<EOF
var 1..5: x;
int: data :: add_to_output = 2;
EOF
minizinc t1.mzn --output-mode json --output-time --output-objective --output-output-item --statistics
minizinc t2.mzn --output-mode json --output-time --output-objective --output-output-item --statistics
```

**Comment by Dekker1** [comment]
I'm afraid I can only provide limited support for this issue as I do not have any machines using these architectures. As these must be exceptions triggered in the MiniZinc compiler, I would suggest running pytest using `--log-cli-level debug` to capture the exact commands used. Then hopefully you can recreate the issue.

**Comment by StefanBruens** [comment]
The following triggers the bug with "pure" minizinc on aarch64:
```
cat > t.mzn <<EOF
var 1..5: x;
EOF
cat > t1.mzc.mzn <<EOF
output["SIMPLE CHECK"];
EOF
minizinc t1.mzc.mzn t.mzn --output-mode json --output-time --output-objective --output-output-item --statistics
```

**Comment by StefanBruens** [comment]
```
[  257s] + gdb -ex start -ex 'catch throw' -ex c -ex bt -ex q --args /home/abuild/rpmbuild/BUILDROOT/libminizinc-2.6.4-lp153.20.1.aarch64//usr/bin/minizinc t2.mzc.mzn t.mzn --verbose --output-mode json --output-time --output-objective --output-output-item --statistics
[  257s] GNU gdb (GDB; SUSE Linux Enterprise 15) 10.1
...
[  257s] Reading symbols from /home/abuild/rpmbuild/BUILDROOT/libminizinc-2.6.4-lp153.20.1.aarch64//usr/bin/minizinc...
[  257s] (No debugging symbols found in /home/abuild/rpmbuild/BUILDROOT/libminizinc-2.6.4-lp153.20.1.aarch64//usr/bin/minizinc)
[  257s] Temporary breakpoint 1 at 0x1d50
[  257s] Starting program: /home/abuild/rpmbuild/BUILDROOT/libminizinc-2.6.4-lp153.20.1.aarch64/usr/bin/minizinc t2.mzc.mzn t.mzn --verbose --output-mode json --output-time --output-objective --output-output-item --statistics
[  257s] [Thread debugging using libthread_db enabled]
[  257s] Using host libthread_db library "/lib64/libthread_db.so.1".
[  257s] 
[  257s] Temporary breakpoint 1, 0x0000aaaaaaaabd50 in main ()
[  257s] Catchpoint 2 (throw)
[  257s] Continuing.
[  257s] 
[  257s] Catchpoint 2 (exception thrown), 0x0000fffff79acecc in __cxa_throw ()
[  257s]    from /usr/lib64/libstdc++.so.6
[  257s] #0  0x0000fffff79acecc in __cxa_throw () from /usr/lib64/libstdc++.so.6
[  257s] #1  0x0000fffff7ee898c in MiniZinc::Plugin::Plugin(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) () from /usr/lib64/libmzn.so
[  257s] #2  0x0000fffff7ee4a18 in XpressPlugin::XpressPlugin() ()
[  257s]    from /usr/lib64/libmzn.so
[  257s] #3  0x0000fffff7ee52b0 in MIPxpressWrapper::checkDLL() ()
[  257s]    from /usr/lib64/libmzn.so
[  257s] #4  0x0000fffff7ee5414 in MIPxpressWrapper::openXpress() ()
[  257s]    from /usr/lib64/libmzn.so
[  257s] #5  0x0000fffff7ee5ca0 in MIPxpressWrapper::getExtraFlags(MIPxpressWrapper::FactoryOptions&) () from /usr/lib64/libmzn.so
[  257s] #6  0x0000fffff7ed7908 in MiniZinc::MIPSolverFactory<MIPxpressWrapper>::factoryOptionsFinished() () from /usr/lib64/libmzn.so
[  257s] #7  0x0000fffff7da30c4 in MiniZinc::MznSolver::processOptions(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () from /usr/lib64/libmzn.so
[  257s] #8  0x0000fffff7da6180 in MiniZinc::MznSolver::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libmzn.so
[  257s] #9  0x0000aaaaaaaac254 in (anonymous namespace)::run(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) ()
[  257s] #10 0x0000aaaaaaaabe74 in main ()

**Comment by StefanBruens** [comment]
Apparently a bug in miniz:
```
[  498s] Thread 1 "minizinc" hit Catchpoint 2 (exception thrown), 0x0000fffff79bcecc in __cxa_throw () from /usr/lib64/libstdc++.so.6
[  498s] $1 = "Catched int"
[  498s] #0  0x0000fffff79bcecc in __cxa_throw () from /usr/lib64/libstdc++.so.6
[  498s] #1  0x0000fffff7c9c6a0 in MiniZinc::FileUtils::inflate_string (s=...) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/lib/file_utils.cpp:736
[  498s] #2  0x0000fffff7da7e20 in MiniZinc::Solns2Out::init (this=this@entry=0xffffffffefd8) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/lib/solns2out.cpp:557
[  498s] #3  0x0000fffff7da890c in MiniZinc::Solns2Out::initFromEnv (this=this@entry=0xffffffffefd8, pE=<optimized out>) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/lib/solns2out.cpp:142
[  498s] #4  0x0000fffff7dade94 in MiniZinc::MznSolver::addSolverInterface (this=this@entry=0xffffffffec30, sf=0xfffff7fbd3b8 <MiniZinc::(anonymous namespace)::get_wrapper()::_fzn_solverfactory>) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/lib/solver.cpp:192
[  498s] #5  0x0000fffff7dadf0c in MiniZinc::MznSolver::addSolverInterface (this=this@entry=0xffffffffec30) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/lib/solver.cpp:212
[  498s] #6  0x0000fffff7db2838 in MiniZinc::MznSolver::run (this=0xffffffffec30, args0=..., model=..., exeName=..., modelName=...) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/lib/solver.cpp:1059
[  498s] #7  0x0000aaaaaaaac254 in (anonymous namespace)::run (exe=..., args=..., jsonStream=false) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/minizinc.cpp:41
[  498s] #8  0x0000aaaaaaaabe74 in main (argc=<optimized out>, argv=0xfffffffff5f8) at /home/abuild/rpmbuild/BUILD/libminizinc-2.6.4/minizinc.cpp:138
[  498s] 
[  498s]   UNKNOWN EXCEPTION in solver, errorcode: -3
```
